### ISSUE TITLE
Question about the eemd-matlab

### ISSUE THREAD

**Issue by yyin17** [liponan/eemd-matlab#1]
Hi there, thanks for sharing the code online.
I couldn't run this code on my PC (Win-7 64bits). I don't know how to change the path and execute ‘mex -I C:/path/to/boost_1_55_0 cpp/eemd.cpp’. Could you explain this more specifically? Thanks!

**Comment by liponan** [comment]
Hello, 
Sorry for the delay in my reply and thanks for sharing the difficulty you experienced.
You need to first download "Boost," a scientific computation library and have it installed, then replace "C:/path/to/boost_1_55_0 cpp/" with its actual installation path.
Hope this helps!
