### ISSUE TITLE
some questions about the version of eemd

### ISSUE THREAD

**Issue by onion5376** [liponan/eemd-matlab#2]
Thanks for sharing your codes. I meet some questions about this. 
Firstly, whether the code "eemd2.m" and eemd3.m" is the same as the multidimensional ensemble empirical mode decomposition (MEEMD) as reportetd in Wu et al. (paper title: The Multi-dimensional ensemble empirial mode decomposition method, 2009). In this paper, MEEMD is used to solve multi-demension data. But, I did not sure whether they are the same.

Secondly, I focused on analyzing the changes in sea surfer temperature （sst）over a given region. The sst data is a time series image (one image for one month, from 2000-2018). So I am confused that how to organized my sst data when applying this program. Run this program to process one image once?

**Comment by liponan** [comment]
`eemd2.m` takes two-dimensional images; `eemd3.m` takes three-dimensional data. Both of them are based on the paper by Wu et al.

As for your second question, that depends on the dimension you are interested in. Are you interested in applying EEMD to the 2D images, or looking into the temporal signal? If both, then you should make your data as a three-dimensional array, and use `eemd3.m`. Hope this helps, and sorry for my belated reply.
