### ISSUE TITLE
question  about goal in EEMD

### ISSUE THREAD

**Issue by saba1989** [liponan/eemd-matlab#3]
Dear Sir
i have used you code for EEMD and I have a question;
i set goal =5  to have 5 IMF (mode), but i see that IMF(mode) has 6 row in fact the eemd code calculate 6 mode for me.
can you explain about goal? what is  the extra mode ?

**Comment by liponan** [comment]
Hi, 

Thanks for your interest in my EEMD code. The extra mode is not from the calculation; it is the residual mode that comes for free. Let's say you have an image A and you request goal=5, then you will end up getting M1, M2, M3, M4, M5 and A - (M1+M2+M3+M4+M5). Hope this helps!

**Comment by saba1989** [comment]
thanks a lot;
so which row show the residual? the 6th row or the first row?
and another issue
Is the "ens" parameter in your code used to calculate the average of the modes? or for another purpose?

**Comment by liponan** [comment]
The residue mode is the last layer, i.e. `img(6, :, :)`. 

`ens` specifies the number of ensembles. If `ens=1`, EMD rather than EEMD will be run.
